### PR TITLE
Adding RFC license.

### PR DESCRIPTION
**Pull request by eranmes**

### CODE REVIEW

**Comment by eranmes** [comment]
@benlaurie PTAL, I've used the IETF RFC license instead of Apache 2.

**Comment by robstradling** [comment]
@eranmes Let's also watch for the outcome of this discussion:
https://mailarchive.ietf.org/arch/search/?q=License+File+for+Open+Source+Repositories

**Comment by robstradling** [comment]
The outcome: https://mailarchive.ietf.org/arch/msg/ietf-announce/9WheAMNLFqe_tJR3cB5zUyBg2AQ

**Comment by richsalz** [comment]
@robstradling I suggest you close this and merge #322.

**Comment by robstradling** [comment]
Closing in favour of #322.

**Pull request closed without merging**
