### PR TITLE
Ticket 102: "root" should be "trust anchor".

### PR DESCRIPTION
**Pull request by robstradling**

### CODE REVIEW

**Comment by benlaurie** [comment]
LGTM, but just want to check that there's really nothing dumb about specifying it this way? Just wondering why no-one pointed it out before I did...

**Comment by robstradling** [comment]
Not dumb at all.  RFC5280 uses the term "trust anchor" a lot, but never uses the term "root certificate".  And as you pointed out, some trust stores include intermediates as well as self-signed root certificates.  e.g. NSS includes this one: https://crt.sh/?id=156583

**Comment by robstradling** [comment]
My guess is that no-one pointed it out before you did because: (i) relatively few people have actually read RFC5280 in detail and (ii) almost all trust anchors are self-signed root certificates and so (iii) no-one who needed this issue with the CT spec to be fixed was actually aware that this issue existed.

**Comment by robstradling** [comment]
Merged at https://github.com/google/certificate-transparency-rfcs/commit/56f42d9c48526798beb848af5c0e7cf1c528f470

**Pull request closed without merging**
