### PR TITLE
Note that a pre-cert SCT can't be returned for the corresponding certifi...

### PR DESCRIPTION
**Pull request by benlaurie**
...cate.

### CODE REVIEW

**Comment by benlaurie** [comment]
@eranmes @robstradling

**Comment by robstradling** [comment]
LGTM

**Comment by benlaurie** [comment]
Pushed at 26354c9.

**Comment by benlaurie** [comment]
Fixes http://trac.tools.ietf.org/wg/trans/trac/ticket/46.

**Pull request closed without merging**
