### PR TITLE
Remove reference targets which are never referenced.

### PR DESCRIPTION
**Pull request by ln5**

### CODE REVIEW

**Comment by ln5** [comment]
Ah. Doing this with my NORDUnet hat on.

**Comment by pphaneuf** [comment]
You might need to change the author of the commit, with some `git commit --amend` tomfoolery?

**Comment by ln5** [comment]
I doubt any email address controlled by me is in Google's CLA database.
I'm letting you know the company's name as per instructions from the bot: NORDUnet A/S.

**Comment by pphaneuf** [comment]
Hmm, we don't appear to have NORDUnet in the corporate CLA signers? I'll have to look into this...

I believe that for corporate CLAs, there's some way for them to list the committer emails that they cover, so the CLA bot would recognise you? But since I don't even see NORDUnet in there, that's not a good start! :wink:

**Comment by pphaneuf** [comment]
Hmm, I can't find NORDUnet either in the current system, or in the old system (before the bot)... I think you'd need someone from NORDUnet to do it? It should be here, for both cases (this should also tell you if you're covered or not, and let you add email aliases and such, as well, once you are indeed covered):

https://cla.developers.google.com/

**Comment by pphaneuf** [comment]
It does look like you used to have an "@nordu.net" email address, though (from a commit you've submitted to the code repo)? But doesn't change that I can't find NORDUnet in either the old or the new corporate CLA databases, sorry...

**Comment by eranmes** [comment]
@ln5 can you confirm if you think NORDUnet has signed the CLA or intends to do so?
(Not sure it's needed, checking internally)

**Comment by ln5** [comment]
@eranmes NORDUnet signed a "software grant and corporate contributer license agreement v1.1" on 2014-06-02. I think it was sent to Google.

**Comment by eranmes** [comment]
Thanks, I'll follow up.

**Comment by richsalz** [comment]
@robstradling you can close this, it's obsolete.

**Pull request closed without merging**
